spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: true
#    hibernate:
#      ddl-auto: update
    session:
      store-type: jdbc
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 80 #다시 8080으로 바꿀 것!
  error:
    include-message: always
    include-binding-errors: always