spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: true
    session:
      store-type: jdbc
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 80 #다시 8080으로 바꿀 것!
  error:
    include-message: always
    include-binding-errors: always