spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: true
    session:
      store-type: jdbc
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: dummy
      secret-key: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy
      voice-file-directory: dummy
