name: TDTD-CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make Directory for deliver
        run: mkdir -p tdtd

      - name: Copy shell script
        run: cp scripts/*.sh tdtd/

      - name: Copy appspec
        run: cp appspec.yml tdtd/

      - name: Copy jar
        run: cp build/libs/*.jar tdtd/

      - name: Make zip file
        run: zip -r tdtd.zip tdtd/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp tdtd.zip s3://tdtd-bucket/TDTD-Deploy/tdtd.zip --region ap-northeast-2

      - name: Code Deploy
        run: aws deploy create-deployment --application-name TDTD --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name tdtd-deploy-group --s3-location bucket=tdtd-bucket,bundleType=zip,key=TDTD-Deploy/tdtd.zip
