name: TDTD-TEST-CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Test Server Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make Directory for deliver
        run: mkdir -p tdtd

      - name: Copy shell script
        run: cp scripts/deploy-test.sh tdtd/

      - name: Copy appspec
        run: cp appspec-test.yml tdtd/

      - name: Copy jar
        run: cp build/libs/*.jar tdtd/

      - name: Make zip file
        run: zip -r tdtd.zip tdtd/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp tdtd.zip s3://tdtd-test-bucket/TDTD-Deploy/tdtd.zip --region ap-northeast-2

      - name: Code Deploy
        run: aws deploy create-deployment --application-name tdtd_test --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name tdtd_test_group --s3-location bucket=tdtd-test-bucket,bundleType=zip,key=TDTD-Deploy/tdtd.zip
